# Generated by Django 3.2 on 2022-04-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
