# Generated by Django 3.2 on 2022-05-03 21:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
