# Generated by Django 3.2 on 2022-05-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_newsletter_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='message',
            field=models.TextField(max_length=3000),
        ),
    ]
