# Generated by Django 3.2 on 2022-05-14 06:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0007_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='slug',
            field=models.SlugField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='slug_end',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
