# Generated by Django 3.2 on 2022-05-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0008_auto_20220514_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
