# Generated by Django 3.2 on 2022-05-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20220501_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating_score',
            field=models.IntegerField(),
        ),
    ]
