# Generated by Django 3.2 on 2022-05-03 13:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_rating_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug_end',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
