# Generated by Django 3.2 on 2022-05-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_slug_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating_score',
            field=models.IntegerField(null=True),
        ),
    ]
