# Generated by Django 3.2 on 2022-05-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promo_total',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
